apiVersion: v1
appVersion: 6.1.0
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: entando-engine
version: 6.1.0
